(define (make-monitored f)
  (let ((count 0))
  (define (how-many-calls) count)
  (define (reset-count) (begin (set! count 0) 0))
  (lambda (type)  
    (cond ((eq? type 'how-many-calls) (how-many-calls))
          ((eq? type 'reset-count) (reset-count))
          (else (f type)
            (set! count (+ 1 count))))))
) 